{
 "title": "Redis",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(up{middleware=\"redis\"},namespace)"
   },
   {
    "name": "service",
    "query": "label_values(up{namespace=\"$namespace\", middleware=\"redis\"}, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(redis_instance_info{service=\"$service\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "总体概况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "节点信息",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "redis_instance_info{namespace=\"$namespace\",service=\"$service\"}"
    }
   ]
  },
  { "title": "连接情况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "实时连接情况",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_config_maxclients{namespace=\"$namespace\",service=~\"$service.*\",pod=\"$pod\"}",
     "legendFormat": "最大连接数 {{instance}}"
    },
    {
     "expr": "sum(redis_connected_clients{namespace=\"$namespace\",service=\"$service\"})",
     "legendFormat": "总连接数"
    },
    {
     "expr": "sum(redis_blocked_clients{namespace=\"$namespace\",service=\"$service\"})",
     "legendFormat": "总阻塞数 "
    },
    {
     "expr": "redis_connected_clients{pod=\"$pod\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "连接数 {{instance}}"
    },
    {
     "expr": "redis_blocked_clients{pod=\"$pod\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "阻塞数 {{instance}}"
    }
   ]
  },
  { "title": "命令执行情况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "instance" },
  {
   "title": "最近一次慢查询耗时",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(redis_last_slow_execution_duration_seconds{namespace=\"$namespace\",service=\"$service\"})"
    }
   ]
  },
  {
   "title": "命令执行数量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_commands_processed_total{namespace=\"$namespace\",service=\"$service\"}) by (cmd)",
     "legendFormat": "{{cmd}}"
    },
    {
     "expr": "redis_commands_processed_total{pod=\"$pod\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "{{cmd}} {{pod}}"
    }
   ]
  },
  {
   "title": "命令执行时间",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by  (cmd)(rate(redis_commands_duration_seconds_total{pod=\"$pod\",namespace=\"$namespace\",service=\"$service\"}[2m])) / sum by (cmd)(rate(redis_commands_total{pod=\"$pod\",namespace=\"$namespace\",service=~\"$service.*\"}[2m]))",
     "legendFormat": "{{cmd}}"
    },
    {
     "expr": "(rate(redis_commands_duration_seconds_total{pod=\"$pod\",namespace=\"$namespace\",service=\"$service\"}[2m])) / (rate(redis_commands_total{pod=\"$pod\",namespace=\"$namespace\",service=~\"$service.*\"}[2m]))",
     "legendFormat": "{{cmd}} {{pod}}"
    }
   ]
  },
  {
   "title": "OPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (irate(redis_commands_total{namespace=\"$namespace\",service=\"$service\"}[1m]))",
     "legendFormat": "ops"
    },
    {
     "expr": "sum by (instance) (irate(redis_commands_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[1m]))",
     "legendFormat": "ops $pod"
    }
   ]
  },
  { "title": "键情况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "key实时情况",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_db_keys{pod=\"$pod\",namespace=\"$namespace\",service=\"$service\"})",
     "legendFormat": "key "
    },
    {
     "expr": "sum(redis_db_keys_expiring{pod=\"$pod\",namespace=\"$namespace\",service=\"$service\"})",
     "legendFormat": "expiring key  "
    },
    {
     "expr": "sum(redis_evicted_keys_total{instance=\"$instance\",namespace=\"$namespace\",service=\"$service\"})",
     "legendFormat": "evicted key"
    },
    {
     "expr": "sum(redis_keyspace_misses_total{instance=\"$instance\",namespace=\"$namespace\",service=\"$service\"})",
     "legendFormat": "misses key"
    },
    {
     "expr": "sum(redis_keyspace_hits_total{instance=\"$instance\",namespace=\"$namespace\",service=\"$service\"})",
     "legendFormat": "hits key"
    }
   ]
  },
  {
   "title": "命中率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_keyspace_hits_total{namespace=\"$namespace\"}) / (sum(redis_keyspace_hits_total{namespace=\"$namespace\"}) + sum(redis_keyspace_misses_total{namespace=\"$namespace\"}))"
    },
    {
     "expr": "sum(redis_keyspace_hits_total{namespace=\"$namespace\",instacne=\"$instance\"}) / (sum(redis_keyspace_hits_total{namespace=\"$namespace\",instacne=\"$instance\"}) + sum(redis_keyspace_misses_total{namespace=\"$namespace\",instacne=\"$instance\"}))",
     "legendFormat": "instance"
    }
   ]
  },
  { "title": "系统资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "内存使用",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{pod=\"$pod\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "内存使用量"
    },
    {
     "expr": "redis_memory_used_rss_bytes{pod=\"$pod\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "应用内存"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{pod=\"$pod\",namespace=\"$namespace\",service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_net_input_bytes_total{pod=\"$pod\",namespace=\"$namespace\",service=\"$service\"}[2m]) * 8)",
     "legendFormat": "入流量"
    },
    {
     "expr": "sum(rate(redis_net_output_bytes_total{pod=\"$pod\",namespace=\"$namespace\",service=\"$service\"}[2m]) * 8)",
     "legendFormat": "出流量"
    }
   ]
  },
  { "title": "哨兵", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "哨兵信息",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "redis_sentinel_master_sentinels"
    }
   ]
  },
  { "title": "cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "messages sent/received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_cluster_messages_received_total{pod=\"$pod\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "receive {{pod}}"
    },
    {
     "expr": "redis_cluster_messages_sent_total{pod=\"$pod\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "sent {{pod}}"
    }
   ]
  },
  {
   "title": "redis_cluster_slots",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "repeat": "pod",
   "targets": [
    { "expr": "redis_cluster_slots_fail" },
    { "expr": "redis_cluster_slots_assigned" }
   ]
  }
 ]
}