# permissions for end users to view RedisCluster.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: RedisCluster-viewer-role
rules:
- apiGroups:
  - redis.middleware.hc.cn
  resources:
  - RedisCluster
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redis.middleware.hc.cn
  resources:
  - RedisCluster/status
  verbs:
  - get
