
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - redis.middleware.hc.cn
  resources:
  - RedisCluster
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.middleware.hc.cn
  resources:
  - RedisCluster/finalizers
  verbs:
  - update
- apiGroups:
  - redis.middleware.hc.cn
  resources:
  - RedisCluster/status
  verbs:
  - get
  - patch
  - update
