redisPassword: dangerous
redisServicePort: 6379

storageSize: 5G
#storageClassName: default

# sentinel/cluster
type: cluster

image:
  repository: swr.cn-east-3.myhuaweicloud.com/harmonycloud
  pullPolicy: IfNotPresent
  redisImageTag: v5.0.8
  exporterImageTag: v1.23.1
  initImageTag: v1
  testImageTag: v0.3


nameOverride: ""
fullnameOverride: ""

# 升级方式
updateStrategy:
  type: AutoReceive

#建议设置pod 内存limit 的80%，单位为mb和gb
redisMaxMemory: 409.6mb

redis:
  replicas: 6
  resources:
    limits:
      cpu: "0.2"
      memory: 512Mi
    requests:
      cpu: "0.2"
      memory: 512Mi

sentinel:
  replicas: 3
  resources:
    requests:
      cpu: 100m
    limits:
      memory: 100Mi

nodeAffinity: {}

podAntiAffinityTopologKey: "kubernetes.io/hostname"

#取值[hard|soft] hard:强制反亲和 soft:非强制反亲和
podAntiAffinity: "soft"



