apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  generation: 1
  labels:
    app: {{ include "redis.fullname" . }}
  name: {{ include "redis.fullname" . }}
spec:
  endpoints:
    - interval: 30s
      port: redis-exporter
      relabelings:
      - replacement: redis
        targetLabel: middleware
      - sourceLabels: [service]
        replacement: {{ include "redis.fullname" . }}
        targetLabel: service
  selector:
    matchLabels:
      app: {{ include "redis.fullname" . }}
